Repository rust-embedded/svd2rust, pull requests merged in 2019-05, with the labels that each got.

#286 Add missing release tags links
  CHANGELOG.md
Labels: S-waiting-on-bors, T-tools

#293 Fix rustc warnings.
  src/generate/peripheral.rs
  src/main.rs
Labels: S-waiting-on-review, T-tools

#298 Added RUST_BACKTRACE=1 to enable backtraces
  ci/script.sh
Labels: S-waiting-on-review, T-tools

#238 Remove debug assert from Peripherals::steal
  src/generate/device.rs
Labels: S-waiting-on-bikeshed
